// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmHFi6P0V-tVm6pLpTfmu1w5QpvAIWLE4',
    appId: '1:251765097007:web:492e3995618a31ef6bbcda',
    messagingSenderId: '251765097007',
    projectId: 'quranic-competition-supabase',
    authDomain: 'quranic-competition-supabase.firebaseapp.com',
    storageBucket: 'quranic-competition-supabase.firebasestorage.app',
    measurementId: 'G-2CP98ZBZ6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs0sbtJe1RAhbUSu5WRfMIky2DxpFJ3bk',
    appId: '1:251765097007:android:9201b1ac54f67e5e6bbcda',
    messagingSenderId: '251765097007',
    projectId: 'quranic-competition-supabase',
    storageBucket: 'quranic-competition-supabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05WMPVGdXsUdFVVxyI0WYLctWT0GNJoI',
    appId: '1:251765097007:ios:cb23a3d7e9482cef6bbcda',
    messagingSenderId: '251765097007',
    projectId: 'quranic-competition-supabase',
    storageBucket: 'quranic-competition-supabase.firebasestorage.app',
    iosBundleId: 'com.coranehel.quranicCompetition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC05WMPVGdXsUdFVVxyI0WYLctWT0GNJoI',
    appId: '1:251765097007:ios:cb23a3d7e9482cef6bbcda',
    messagingSenderId: '251765097007',
    projectId: 'quranic-competition-supabase',
    storageBucket: 'quranic-competition-supabase.firebasestorage.app',
    iosBundleId: 'com.coranehel.quranicCompetition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmHFi6P0V-tVm6pLpTfmu1w5QpvAIWLE4',
    appId: '1:251765097007:web:4c64b228ebd915976bbcda',
    messagingSenderId: '251765097007',
    projectId: 'quranic-competition-supabase',
    authDomain: 'quranic-competition-supabase.firebaseapp.com',
    storageBucket: 'quranic-competition-supabase.firebasestorage.app',
    measurementId: 'G-E75G8V17FM',
  );
}

