# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build release AAB (Android App Bundle)"
  lane :build_release do
    gradle(
      task: "clean bundleRelease",
      project_dir: "."
    )
  end

  desc "Build release APK"
  lane :build_apk do
    gradle(
      task: "clean assembleRelease",
      project_dir: "."
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to Google Play (Internal Testing)"
  lane :deploy_internal do
    gradle(
      task: "clean bundleRelease",
      project_dir: "."
    )
    
    upload_to_play_store(
      track: "internal", # internal, alpha, beta, production
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy a new version to Google Play (Production)"
  lane :deploy do
    gradle(
      task: "clean bundleRelease",
      project_dir: "."
    )
    
    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to Alpha track"
  lane :deploy_alpha do
    gradle(
      task: "clean bundleRelease",
      project_dir: "."
    )
    
    upload_to_play_store(
      track: "alpha",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to Beta track"
  lane :deploy_beta do
    gradle(
      task: "clean bundleRelease",
      project_dir: "."
    )
    
    upload_to_play_store(
      track: "beta",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
